"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { LayoutDashboard, Smile, BookOpen, MessageCircle, Flame, ClipboardList, BarChart3, Settings } from "lucide-react";
import { GradientBackground } from "@/components/ui/GradientBackground";
import { AppProvider } from "@/hooks/useAppStore";
const NAV=[{h:"/",l:"Dashboard",I:LayoutDashboard},{h:"/mood",l:"Mood",I:Smile},{h:"/journal",l:"Journal",I:BookOpen},{h:"/coach",l:"Coach",I:MessageCircle},{h:"/burnout",l:"Burnout",I:Flame},{h:"/plan",l:"Plan",I:ClipboardList},{h:"/insights/weekly",l:"Insights",I:BarChart3}];
function Sidebar(){const p=usePathname();return(<aside className="glass-strong hidden lg:flex lg:w-[280px] lg:flex-col lg:border-r lg:border-border lg:p-5"><div className="mb-8 px-2"><h1 className="font-display text-xl font-bold text-gradient">MindMirror</h1><p className="mt-1 text-xs text-muted">AI Wellness Companion</p></div><nav className="flex flex-col gap-1">{NAV.map(({h,l,I})=>{const a=p===h||(h!=="/"&&p.startsWith(h));return(<Link key={h} href={h} className={`relative flex items-center gap-3 rounded-2xl px-3 py-2.5 text-sm font-medium ${a?"bg-primary-subtle text-primary":"text-muted hover:bg-surface hover:text-foreground"}`}>{a&&<span className="absolute left-0 top-1/2 h-5 w-1 -translate-y-1/2 rounded-full bg-primary"/>}<I className="h-4 w-4"/>{l}</Link>);})}<Link href="/insights/triggers" className={`ml-7 px-3 py-2 text-xs ${p==="/insights/triggers"?"text-primary":"text-subtle"}`}>Stress Triggers</Link></nav><div className="mt-auto pt-4"><Link href="/settings" className={`flex items-center gap-3 rounded-2xl px-3 py-2.5 text-sm ${p==="/settings"?"bg-primary-subtle text-primary":"text-muted"}`}><Settings className="h-4 w-4"/>Settings</Link></div></aside>);}
function BottomNav(){const p=usePathname();return(<nav className="fixed bottom-0 left-0 right-0 z-50 px-4 pb-4 lg:hidden"><div className="glass-strong flex justify-around rounded-[28px] px-2 py-2">{NAV.slice(0,5).map(({h,l,I})=>(<Link key={h} href={h} className={`flex min-h-[44px] flex-col items-center justify-center text-xs ${p===h?"text-primary":"text-muted"}`}><I className="h-5 w-5"/><span>{l}</span></Link>))}</div></nav>);}
export function AppShell({children}:{children:React.ReactNode}){return(<AppProvider><GradientBackground /><div className="flex min-h-screen"><Sidebar /><div className="flex flex-1 flex-col"><main id="main-content" className="flex-1 px-5 py-8 pb-28 lg:px-10 lg:py-10 lg:pb-10">{children}</main><BottomNav /></div></div></AppProvider>);}
